### ISSUE TITLE
New Akamai transaction URLs

### ISSUE THREAD

**Issue by fulv** [collective/getpaid.authorizedotnet#1]
See http://app.payment.authorize.net/e/es.aspx?s=986383348&e=918505&elq=dda798aec8a1415fb21e2fdecaccb96b

By June 2016, all transaction processing URLs will be automatically redirected to connect through Akamai.  So, strictly speaking, changing the URLs should not be required.  However, it says:

**IMPORTANT: To take advantage of the uptime benefits Akamai offers, we recommend you proactively update your website or payment solution during Phase One rather than waiting to be automatically updated during Phase Two.**
## Updating Your Solution

The new Akamai transaction URLs that are available now are:
- https://api2.authorize.net/xml/v1/request.api
- https://api2.authorize.net/soap/v1/Service.asmx
- https://secure2.authorize.net/gateway/transact.dll

I'm going to change the URLs in a branch and test.

**Comment by davisagli** [comment]
Thanks for testing. I think the main question is whether the new URLs use the same certificates or not.

**Comment by fulv** [comment]
It works with the new URLs, so they must be using the same certificates.

**Comment by davisagli** [comment]
Great. If you merge the change I can make a release.

**Comment by davisagli** [comment]
FYI, looks like Authorize.net has an official Python SDK in beta: https://github.com/AuthorizeNet/sdk-python

**Comment by davisagli** [comment]
I finally got around to releasing 0.6.8

**Comment by fulv** [comment]
Thank you!
